publish_to: none
name: pixelart_client
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:

  http: ^1.1.0
  json_annotation: ^4.8.1
  mocktail: ^1.0.0
  uuid: ^4.1.0
  web_socket_channel: ^2.4.0
  pixelart_shared:
    path: '../pixelart_shared'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
